import type { ProjectEvaluation } from "@/lib/contract/types";
import { badgeSvg } from "@/lib/badge/badge";

// README badge share block (WEB-003). The SVG is generated by the pure badge
// function with every field escaped, so inlining it is safe. The badge and its
// markdown snippet link back to the matching engine-specific result.

function projectId(evaluation: ProjectEvaluation): string {
  const src = evaluation.project.source;
  return src.kind === "hosted"
    ? `${src.namespace}/${src.repository}`
    : src.repository_id;
}

export function BadgeShare({ evaluation }: { evaluation: ProjectEvaluation }) {
  const id = projectId(evaluation);
  const svg = badgeSvg(evaluation);
  const badgePath = `/badge/${id}`;
  const resultPath = `/evaluations/${id}`;
  const markdown = `[![Assay](${badgePath})](${resultPath})`;

  return (
    <section aria-labelledby="share-badge">
      <h2 id="share-badge">Share this result</h2>
      <p className="muted">
        The badge states the engine profile, score, and provisional, stale, or
        insufficient-evidence state, and links to this engine-specific result.
      </p>

      <div className="badge-preview" dangerouslySetInnerHTML={{ __html: svg }} />

      <label htmlFor="badge-markdown">README markdown</label>
      <input id="badge-markdown" type="text" readOnly value={markdown} />
      <p className="muted">
        Prefix the badge and result paths with the deployment origin when
        embedding in a remote README.
      </p>
    </section>
  );
}
